# Generated by Django 5.0.3 on 2024-04-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="password",
        ),
    ]
