# Generated by Django 5.0.3 on 2024-04-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_users_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="password",
            field=models.CharField(default=12345678, max_length=128),
            preserve_default=False,
        ),
    ]
