# Generated by Django 5.0.3 on 2024-04-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_users_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="user_name",
            new_name="username",
        ),
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
    ]
