# Generated by Django 5.0.3 on 2024-04-04 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_user_name_users_username_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users",
        ),
    ]
