# Generated by Django 5.0.3 on 2024-05-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0002_label_created_at_label_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
