# Generated by Django 5.0.3 on 2024-04-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0002_statuses_is_active_alter_statuses_name"),
        ("tasks", "0002_task_autor"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.ManyToManyField(to="statuses.statuses"),
        ),
    ]
