# Generated by Django 5.0.3 on 2024-04-08 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="executor",
            field=models.ManyToManyField(
                related_name="executed_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="autor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="autor_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
