# Generated by Django 5.0.3 on 2024-04-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_executor_alter_task_autor"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(default="description"),
        ),
    ]
