# Generated by Django 5.0.3 on 2024-04-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_task_created_at_task_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="tags",
            new_name="Label",
        ),
    ]
