# Generated by Django 5.0.3 on 2024-04-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_rename_tags_task_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="Label",
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.TextField(default="labels"),
        ),
    ]
