# Generated by Django 5.0.3 on 2024-04-09 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_alter_task_autor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default="description"),
        ),
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ManyToManyField(
                blank=True, related_name="executed_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="labels",
            field=models.TextField(blank=True, default="labels"),
        ),
    ]
