# Generated by Django 5.0.3 on 2024-04-09 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_alter_task_description_alter_task_executor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ManyToManyField(
                blank=True,
                default=[],
                related_name="executed_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
