# Generated by Django 5.0.3 on 2024-04-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuses",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="statuses",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
