# Generated by Django 5.0.3 on 2024-04-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0002_statuses_is_active_alter_statuses_name"),
        ("tasks", "0004_alter_task_executor"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Statuses",
            new_name="Status",
        ),
    ]
