# Generated by Django 5.0.3 on 2024-04-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0003_rename_statuses_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status",
            name="is_active",
        ),
    ]
