# Generated by Django 5.0.3 on 2024-05-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0004_remove_status_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
