# Generated by Django 5.0.3 on 2024-05-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0005_alter_status_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
